### ISSUE TITLE
Register/Sign Up screen responsiveness

### ISSUE THREAD

**Issue by jojosuelobo** [jojosuelobo/eng-lab-soft#20]
Update files related to the Register screen for the purpose of making the screen responsive on mobile devices.
Width Breakpoint: lower than 677px
_The logo image it's on `public\logo.png`_
_url: http://localhost:5173/register_

Figma page reference
![image](https://github.com/jojosuelobo/eng-lab-soft/assets/47835727/53b72b93-88f1-4dd0-97d9-3791a87f808b)

**Comment by Sky-De** [comment]
@jojosuelobo hi, assign this to me
Thanks

**Comment by jojosuelobo** [comment]
> @jojosuelobo hi, assign this to me Thanks

You can fork the project and after changes open a PR

**Comment by Sky-De** [comment]
@jojosuelobo actually I'm working on couple of different open source project, also i keep track of these contributions within assignment tab
 i will start working on this as soon as i get assigned to it.
Thanks for understanding
